### PR TITLE
ccls 0.20180924

### PR DESCRIPTION
**Pull request by MindTooth**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MindTooth** [comment]
Did not know the command worked for taps. 👍 

Though, I needed to add my own remote first.  Other than that, worked like a charm with `brew bump-pr-formula`.

```
 brew bump-formula-pr ccls --revision=41fcc0272c8c93fcbe52f24ef587e633a9dcc7e1 --tag=0.20180924 --verbose
```

**Comment by twlz0ne** [comment]
@MindTooth

I just added Travis to this project but seems it doesn't work for existing PR.

Would you mind to push again? I want to confirm if Travis works.

```sh
git commit --amend # No need to change anything, just for generate new commit hash
git push origin ccls-0.20180924 --force
```
Thanks.

**Comment by MindTooth** [comment]
That crashed and burned. 😆 

1: The test case is broken.  `--test-unit` is not an acceptable option.
2:  Complains about downgrade on El Capitan.

Ed1t:  Also, it takes ages to run through.  Is caching `/usr/local/Homebrew` an option?

**Comment by twlz0ne** [comment]
@MindTooth 

> 1: The test case is broken. `--test-unit` is not an acceptable option.

I'll replace it with `--help`. 

> 2: Complains about downgrade on El Capitan.

I have no idea why this happens.

**Pull request merged**
